# Generated by Django 3.0.8 on 2020-07-25 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20200705_2153'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='product_image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.ProductImage', verbose_name='Продукт'),
        ),
    ]
