# Generated by Django 3.0.8 on 2020-07-25 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20200725_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='is_recommended',
            field=models.BooleanField(default=True, verbose_name='Главный?'),
        ),
    ]
