# Generated by Django 3.0.8 on 2020-08-06 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_feedback_is_recommended'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='content',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Описание'),
        ),
    ]
